<?php

return [

    // Application name (used in emails, notifications, UI)
    'name' => env('APP_NAME', 'Laravel'),

    // Application environment (local, production, testing)
    'env' => env('APP_ENV', 'production'),

    // Debug mode (true = show errors, false = hide errors)
    'debug' => (bool) env('APP_DEBUG', false),

    // Application URL (used for generating links in emails and commands)
    'url' => env('APP_URL', 'http://localhost'),

    // Default timezone for dates and times
    'timezone' => 'UTC',

    // Language settings
    'locale' => env('APP_LOCALE', 'en'),
    'fallback_locale' => env('APP_FALLBACK_LOCALE', 'en'),
    'faker_locale' => env('APP_FAKER_LOCALE', 'en_US'),

    // Encryption settings (generated by 'php artisan key:generate')
    'cipher' => 'AES-256-CBC',
    'key' => env('APP_KEY'),
    'previous_keys' => [
        ...array_filter(
            explode(',', (string) env('APP_PREVIOUS_KEYS', ''))
        ),
    ],

    // Maintenance mode settings (file or cache)
    'maintenance' => [
        'driver' => env('APP_MAINTENANCE_DRIVER', 'file'),
        'store' => env('APP_MAINTENANCE_STORE', 'database'),
    ],

];
